---
- name: Install default Apache Web Server
  hosts: Linux
  become: yes
    
  vars:
   source_file: ./index.html
   destination_file: /var/www/html

  tasks:
  - name: Apt install Apache
    apt: name=apache2 update_cache=yes state=latest

  - name: Copy files to server
    copy: src={{ source_file }} dest={{ destination_file }} mode=0555
    notify: Restart

  - name: Start and Enable Apache
    service: name=apache2 state=started enabled=yes 
  
  handlers:
  - name: Restart
    service: name=apache2 state=restarted
